# Java Gradle CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
jobs:
  build:
    branches:
      only:
      - master
    docker:
    # specify the version you desire here
    - image: circleci/openjdk:8-jdk

    working_directory: ~/workdir

    environment:
      # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx3200m
      TERM: dumb

    steps:
    - checkout
    - run:
        name: Build bufi
        working_directory: ~/workdir/bufi/
        command: ./gradlew jar
    - run:
        name: Generate snippets
        working_directory: ~/workdir/bufi/build/libs/
        command: java -jar ./bufi-1.0.jar
    - deploy:
        name: Trigger snippet deployment
        working_directory: ~/workdir
        command: |

          git config credential.helper 'cache --timeout=120'
          git config user.email "<email>"
          git config user.name "Deployment Bot"
          echo '---git status ----'
          git status
          echo '---git checkout prod ----'
          git checkout prod
          mv -f quick.json api/quick.json
          mv -f full.json api/full.json
          echo '---git add files ----'
          git add api/quick.json
          git add api/full.json
          echo '---git commit ----'
          git commit --allow-empty -m "Generating snippets"
          # Push quietly to prevent showing the token in log
          echo '---git push it ----'
          git push -f -q https://${DOCS_GITHUB_TOKEN}@github.com/eltonkola/androidz.git prod
